version: '3.3'                 # docker-composeのversionを指定
services:
  db:
    image: mysql:5.7
    container_name: aiueo
    restart: always
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql  #MySQLデータ
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
      - .log/mysql:/var/log/mysql