server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restful_api
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    sql-script-encoding: utf-8

  profiles:
    active: local

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
      enabled: true
      max-file-size: 100KB

  messages:
    basename: messages
    cache-duration: -1
    encoding: UTF-8

  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: false

  jackson:
    default-property-inclusion: non_null

config:
  access-token:
    usableMinutes: 30
    authorizationHeaderFormat: "Bearer"

settings:
  log:
    extension: .tsv

frontend:
  url: http://localhost:3000

clientId: ${GITHUB_CLIENTID}
clientSecret: ${GITHUB_CLIENTSECRET}
callbackUrl: http://localhost:8080/github/callback

#==================================================================
# AWS設定
#==================================================================
cloud.aws:
  region:
    static: ap-northeast-1
  stack:
    auto: false
  credentials:
    # .envで指定したminioのキー
    accessKey: local-dummy-access-key
    secretKey: local-dummy-secret-key
  endPointUrl: http://127.0.0.1:9000

aws:
  bucket:
    name: "asadahyuma-product-image"

clientConfiguration:
  connectionTimeoutSec: 10000
  clientExecutionTimeoutSec: 10000
  requestTimeoutSec: 10000
  socketTimeoutSec: 10000
  maxErrorRetryCount: 5
  protocol: HTTPS
  useGzip: true