server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://asdahyuma-mysql-5-7.c35xcnhiknum.ap-northeast-1.rds.amazonaws.com/asadahyuma_db
    username: admin
    password: hyuma0309
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    sql-script-encoding: utf-8

  profiles:
    active: production

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
      enabled: true
      max-file-size: 100KB

  messages:
    basename: messages
    cache-duration: -1
    encoding: UTF-8

  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: false

  jackson:
    default-property-inclusion: non_null

config:
  access-token:
    usableMinutes: 30
    authorizationHeaderFormat: "Bearer"

settings:
  log:
    extension: .tsv

clientId: ${GITHUB_CLIENTID}
clientSecret: ${GITHUB_CLIENTSECRET}
callbackUrl: http://ec2-35-72-4-237.ap-northeast-1.compute.amazonaws.com/github/callback

uploadDir: src/main/resources/static/image/