server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://asdahyuma-mysql-5-7.c35xcnhiknum.ap-northeast-1.rds.amazonaws.com:3306/asadahyuma_db
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    sql-script-encoding: utf-8

  profiles:
    active: production

  jpa:
    database: MYSQL
    open-in-view: false
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
      enabled: true
      max-file-size: 100KB

  messages:
    basename: messages
    cache-duration: -1
    encoding: UTF-8

  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: false

  jackson:
    default-property-inclusion: non_null

config:
  access-token:
    usableMinutes: 30
    authorizationHeaderFormat: "Bearer"

settings:
  log:
    extension: .tsv

frontend:
  url: https://www.tle-dev-asadahyuma.com

clientId: ${GITHUB_CLIENTID}
clientSecret: ${GITHUB_CLIENTSECRET}
callbackUrl: https://tle-dev-asadahyuma.com/github/callback

#==================================================================
# AWS設定
#==================================================================
cloud.aws:
  endPointUrl: https://s3-ap-northeast-1.amazonaws.com


aws:
  bucket:
    name: "tle-dev-asadahyuma"
